language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t thluiz10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thluiz10/react-test npm run test -- --coverage

after_success:
  - docker build -t thluiz10/multi-client ./client
  - docker build -t thluiz10/multi-nginx ./client
  - docker build -t thluiz10/multi-server ./client
  - docker build -t thluiz10/multi-worker ./client
  #Login no docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push das imagens pro docker hub
  - docker push thluiz10/multi-client
  - docker push thluiz10/multi-nginx
  - docker push thluiz10/multi-server
  - docker push thluiz10/multi-worker

#Pra usar quando tiver cartão pro aws
#Os carinhas em branco tem que completar com as infos depois
#deploy:
# provider: elasticbeanstalk
# region:
# app: docker-react
# env: Docker-env
# bucket_name:
# bucket_path:
# on:
#   branch: master
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key:
#   secure: $AWS_SECRET_KEY